### ISSUE TITLE
Wrong format

### ISSUE THREAD

**Issue by tiosphere** [jtlantz/se-p1-backend#1]
I think it should return JSON format

https://github.com/jtlantz/se-p1-backend/blob/a652e831c3a1a3e50451ccaee4c7d64a1c6e676b/app/backend/api/views.py#L21

**Comment by jtlantz** [comment]
fixed here
https://github.com/jtlantz/se-p1-backend/commit/9ea46ba0ba4f63972ed1a1cd2b6806b47c83518d
