### ISSUE TITLE
Naming Convention (Snake Case)

### ISSUE THREAD

**Issue by CodePan1** [jtlantz/se-p1-backend#2]
https://github.com/jtlantz/se-p1-backend/blob/a652e831c3a1a3e50451ccaee4c7d64a1c6e676b/app/backend/api/views.py#L24

minor thing about naming functions, according to PEP 8: vendingMachine → vending_machine

**Comment by jtlantz** [comment]
fixed here
https://github.com/jtlantz/se-p1-backend/commit/791b3aa2b20b4689e286cdff77f57868b5004d43
